#!/usr/bin/env bash
set -euo pipefail

RELEASE_VERSION="${1:-}"
if [[ -z "${RELEASE_VERSION}" ]]; then
  echo "usage: scripts/release-dry-run.sh <release-version>" >&2
  exit 2
fi

if [[ ! "${RELEASE_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "invalid release version '${RELEASE_VERSION}' (expected semver-like value, example: 0.2.0)" >&2
  exit 2
fi

node_version="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' ditto-nodejs-client/package.json | head -n 1)"
python_version="$(sed -n 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' ditto-python-client/pyproject.toml | head -n 1)"
java_version="$(sed -n 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' ditto-java-client/build.gradle.kts | head -n 1)"

if [[ -z "${node_version}" || -z "${python_version}" || -z "${java_version}" ]]; then
  echo "failed to parse one or more SDK versions from source files" >&2
  exit 1
fi

echo "Release dry-run target version: ${RELEASE_VERSION}"
echo "Current versions:"
echo "  Node.js : ${node_version} (ditto-nodejs-client/package.json)"
echo "  Python  : ${python_version} (ditto-python-client/pyproject.toml)"
echo "  Java    : ${java_version} (ditto-java-client/build.gradle.kts)"
echo "  Go      : module version follows git tag (go.mod has no package version field)"
echo

if [[ "${node_version}" != "${python_version}" || "${node_version}" != "${java_version}" ]]; then
  echo "warning: SDK source versions are currently not aligned across Node/Python/Java" >&2
fi

last_tag="$(git tag --list "client-v*" --sort=-creatordate | head -n 1 || true)"
range_spec=""
if [[ -n "${last_tag}" ]]; then
  range_spec="${last_tag}..HEAD"
  echo "Changelog baseline tag: ${last_tag}"
else
  range_spec="HEAD"
  echo "Changelog baseline tag: <none> (using full history in this clone)"
fi

{
  echo "# Changelog Preview for v${RELEASE_VERSION}"
  echo
  echo "Generated by \`scripts/release-dry-run.sh\`."
  echo
  if [[ -n "${last_tag}" ]]; then
    echo "Range: \`${last_tag}..HEAD\`"
  else
    echo "Range: \`HEAD\` (no \`client-v*\` tag found)"
  fi
  echo
  git log --no-merges --pretty='- %h %s' ${range_spec}
} > release-dry-run-changelog.md

echo "Created changelog preview: release-dry-run-changelog.md"
echo
echo "Planned manual bump targets for v${RELEASE_VERSION}:"
echo "  - ditto-nodejs-client/package.json -> version = ${RELEASE_VERSION}"
echo "  - ditto-python-client/pyproject.toml -> version = ${RELEASE_VERSION}"
echo "  - ditto-java-client/build.gradle.kts -> version = ${RELEASE_VERSION}"
echo "  - create git tag: client-v${RELEASE_VERSION}"
